# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Fit a single ridge regression model
#'
#' @param X First value
#' @param y Second value
#' @param lambda 
#' @return Vector of penalised regression coefficients
#' @export
fit_rr <- function(X, y, lambda) {
    .Call(`_RcppRidge_fit_rr`, X, y, lambda)
}

#' Calculate leave one out cross validation error (OCV) 
#'
#' @param X First value
#' @param y Second value
#' @param lambda 
#' @export
get_ocv <- function(X, y, lambda) {
    .Call(`_RcppRidge_get_ocv`, X, y, lambda)
}

#' Find the optimal regularisation parameter through optimised leave one out cross validation
#'
#' @param v1 First value
#' @param v2 Second value
#' @return Product of v1 and v2
#' @export
optim_rr <- function(X, y, lams) {
    .Call(`_RcppRidge_optim_rr`, X, y, lams)
}

#' Fit a ridge regression model to multiple groups in parallel
#'
#' @param X First value
#' @param y Second value
#' @param lams First value
#' @param idx Second value
#' @return List
#' @export
par_reg <- function(X, y, lams, idx) {
    .Call(`_RcppRidge_par_reg`, X, y, lams, idx)
}

#' Sample from a multivariate Gaussian
#'
#' @param n First value
#' @param mu Second value
#' @param sigma
#' @return matrix 
#' @export
rmvn_omp <- function(n, mu, sigma) {
    .Call(`_RcppRidge_rmvn_omp`, n, mu, sigma)
}

